[tool.djlint]
profile="django"
ignore="H030,H031"
max_line_length=50
use_gitignore=true
format_attribute_template_tags=true
blank_line_before_tag="load, extends, include, for, if, block"
blank_line_after_tag="load, extends, include, endfor, endif, endblock"
