# Generated by Django 4.1.4 on 2022-12-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterclasses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name="masterclass",
            name="category",
            field=models.ManyToManyField(to="masterclasses.category"),
        ),
    ]
