# Generated by Django 4.1.4 on 2022-12-27 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterclasses", "0003_alter_masterclass_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profi",
            name="tel",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
