# Generated by Django 4.1.4 on 2022-12-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterclasses", "0004_alter_profi_tel"),
    ]

    operations = [
        migrations.AddField(
            model_name="masterclass",
            name="description",
            field=models.TextField(default="", max_length=120),
        ),
    ]
