# Generated by Django 4.1.4 on 2022-12-27 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masterclasses", "0006_alter_masterclass_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masterclass",
            name="description",
            field=models.TextField(
                max_length=120,
                validators=[django.core.validators.MinLengthValidator(12)],
            ),
        ),
    ]
