# Generated by Django 4.1.4 on 2022-12-27 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("masterclasses", "0007_alter_masterclass_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="masterclass",
            name="date",
        ),
        migrations.CreateModel(
            name="MasterclassDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "masterclass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="masterclasses.masterclass",
                    ),
                ),
            ],
        ),
    ]
