# Generated by Django 4.1.4 on 2022-12-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0011_alter_masterclass_mc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterclass_date', models.DateField()),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='masterclass',
            name='private_students',
            field=models.ManyToManyField(to='masterclasses.privatestudent'),
        ),
    ]
