# Generated by Django 4.1.4 on 2022-12-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0012_privatestudent_masterclass_private_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
