# Generated by Django 4.1.4 on 2022-12-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0014_alter_masterclass_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='category',
            field=models.ManyToManyField(blank=True, to='masterclasses.category'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='private_students',
            field=models.ManyToManyField(blank=True, to='masterclasses.privatestudent'),
        ),
    ]
