# Generated by Django 4.1.4 on 2022-12-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0016_alter_masterclass_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='masterclasses/static/covers'),
        ),
    ]
