# Generated by Django 4.1.4 on 2022-12-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0017_alter_masterclass_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='static/covers'),
        ),
    ]
