# Generated by Django 4.1.4 on 2022-12-29 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0020_alter_masterclass_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
